server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  port: 8080
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    url: /openapi
    use-root-path: true
    docExpansion: none
